apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: openclaw-headers
  namespace: management
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Host: "claw.mvgates.com"
    browserXssFilter: true
    contentTypeNosniff: true
