apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-api-keys
  namespace: management
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: openclaw-secrets
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: GITHUB_TOKEN
    - secretKey: virtual_key
      remoteRef:
        key: LITELLM_VIRTUAL_KEY
    - secretKey: gateway_token
      remoteRef:
        key: OPENCLAW_GATEWAY_TOKEN
